# Generated by Django 4.1.5 on 2023-01-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
                ('title', models.TextField(verbose_name='title')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
