# Generated by Django 4.1.5 on 2023-01-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('director', 'director'), ('accountant', 'accountant'), ('staff', 'staff')], max_length=50, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='staff.specilaty', verbose_name='specialty'),
        ),
    ]
