# Generated by Django 4.1.5 on 2023-01-25 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_alter_staff_position_alter_staff_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffcontactinfo',
            name='staff',
        ),
        migrations.AddField(
            model_name='staffcontactinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_contact_info', to=settings.AUTH_USER_MODEL, verbose_name='staff'),
        ),
    ]
