# Generated by Django 4.1.5 on 2023-01-25 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0003_remove_staffcontactinfo_staff_staffcontactinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffcontactinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_contact_info', to=settings.AUTH_USER_MODEL, verbose_name='staff'),
        ),
    ]
