# Generated by Django 4.1.5 on 2023-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classcategory',
            name='id',
        ),
        migrations.AddField(
            model_name='classcategory',
            name='slug',
            field=models.SlugField(default='b', primary_key=True, serialize=False, verbose_name='slug'),
        ),
    ]
