# Generated by Django 4.1.5 on 2023-01-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='title')),
                ('amount_usd', models.FloatField(verbose_name='amount usd')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_usd', models.FloatField(verbose_name='payment amount')),
                ('payment_usd_left', models.FloatField(verbose_name='payment left')),
                ('paid', models.FloatField(verbose_name='paid')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='fee.discount', verbose_name='discount')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('amount_usd', models.FloatField(verbose_name='amount usd')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'verbose_name': 'Fee category',
                'verbose_name_plural': 'Fee categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
                ('title', models.TextField(verbose_name='title')),
            ],
            options={
                'verbose_name': 'Payment category',
                'verbose_name_plural': 'Payments categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='slug')),
                ('title', models.TextField(verbose_name='title')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='fee.fee', verbose_name='fee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='student.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Payment plan',
                'verbose_name_plural': 'Payment plans',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.FloatField(blank=True, null=True, verbose_name='amount usd')),
                ('rate', models.FloatField(blank=True, null=True, verbose_name='rate')),
                ('amount_kgz', models.FloatField(blank=True, null=True, verbose_name='amount usd')),
                ('who_paid', models.TextField(verbose_name='who paid')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='date')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fee.fee', verbose_name='fee')),
                ('payment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fee.paymentcategory', verbose_name='payment category')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fee.paymenttype', verbose_name='payment type')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='student.student', verbose_name='student')),
            ],
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='fee.feecategory', verbose_name='fee category'),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='student.student', verbose_name='student'),
        ),
    ]
