# Generated by Django 4.1.5 on 2023-01-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Payment type', 'verbose_name_plural': 'Payment types'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='paid',
            field=models.FloatField(default=0, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_usd',
            field=models.FloatField(default=0, verbose_name='payment amount'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='payment_usd_left',
            field=models.FloatField(default=0, verbose_name='payment left'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
    ]
