# Generated by Django 4.1.5 on 2023-01-22 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='student.student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='session.session', verbose_name='admission year'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('graduated', 'graduated'), ('out of', 'out of'), ('not confirmed', 'not confirmed'), ('active', 'active'), ('pre-registered', 'pre-registered')], max_length=50, verbose_name='status'),
        ),
    ]
