name: build-project-time

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: self-hosted

    steps:
    
    
#       - name: cleanup
#         run : |
#           sudo chown -R $USER:$USER $GITHUB_WORKSPACE 

      - uses: AutoModality/action-clean@v1   
      - uses: actions/checkout@v2
    
      - name: Stop tutor-usa_web_1 container
        run: | 
            docker stop tutor-usa_web_1 
      - name: Stop tutorial-usa_db_1 container
        run: | 
           docker stop tutor-usa_db_1
          
      - name: Delete tutor-usa_db_1 container
        run: |
          docker rm tutor-usa_web_1 
          
      - name: Delete tutor-usa_db_1 container
        run: |
           docker rm tutor-usa_db_1
            
      - name: Makemigrations
        run: |
          docker-compose run web python3 manage.py makemigrations
          
      - name: Migrate
        run: |
          docker-compose run web python3 manage.py migrate
          
      - name: Collectstatic
        run: |
          docker-compose run web python3 manage.py collectstatic 
          
      - name: Run Docker-Compose
        run: |
          docker-compose up -d
